package com.example.model

data class Surah(
    val number: Int,
    val nameArabic: String,
    val nameEnglish: String,
    val englishTranslation: String,
    val revelationType: RevelationType,
    val totalVerses: Int,
    val startingJuz: Int = 1
) {
    val formattedNumber: String
        get() = "%03d".format(number)

    enum class RevelationType(val english: String, val arabic: String) {
        MECCAN("Meccan", "مكية"),
        MEDINAN("Medinan", "مدنية")
    }

    companion object {
        val ALL_SURAHS: List<Surah> = listOf(
            Surah(1, "الفاتحة", "Al-Fatihah", "The Opening", RevelationType.MECCAN, 7, 1),
            Surah(2, "البقرة", "Al-Baqarah", "The Cow", RevelationType.MEDINAN, 286, 1),
            Surah(3, "آل عمران", "Ali 'Imran", "Family of Imran", RevelationType.MEDINAN, 200, 3),
            Surah(4, "النساء", "An-Nisa", "The Women", RevelationType.MEDINAN, 176, 4),
            Surah(5, "المائدة", "Al-Ma'idah", "The Table Spread", RevelationType.MEDINAN, 120, 6),
            Surah(6, "الأنعام", "Al-An'am", "The Cattle", RevelationType.MECCAN, 165, 7),
            Surah(7, "الأعراف", "Al-A'raf", "The Heights", RevelationType.MECCAN, 206, 8),
            Surah(8, "الأنفال", "Al-Anfal", "The Spoils of War", RevelationType.MEDINAN, 75, 9),
            Surah(9, "التوبة", "At-Tawbah", "The Repentance", RevelationType.MEDINAN, 129, 10),
            Surah(10, "يونس", "Yunus", "Jonah", RevelationType.MECCAN, 109, 11),
            Surah(11, "هود", "Hud", "Hud", RevelationType.MECCAN, 123, 11),
            Surah(12, "يوسف", "Yusuf", "Joseph", RevelationType.MECCAN, 111, 12),
            Surah(13, "الرعد", "Ar-Ra'd", "The Thunder", RevelationType.MEDINAN, 43, 13),
            Surah(14, "إبراهيم", "Ibrahim", "Abraham", RevelationType.MECCAN, 52, 13),
            Surah(15, "الحجر", "Al-Hijr", "The Rocky Tract", RevelationType.MECCAN, 99, 14),
            Surah(16, "النحل", "An-Nahl", "The Bee", RevelationType.MECCAN, 128, 14),
            Surah(17, "الإسراء", "Al-Isra", "The Night Journey", RevelationType.MECCAN, 111, 15),
            Surah(18, "الكهف", "Al-Kahf", "The Cave", RevelationType.MECCAN, 110, 15),
            Surah(19, "مريم", "Maryam", "Mary", RevelationType.MECCAN, 98, 16),
            Surah(20, "طه", "Ta-Ha", "Ta-Ha", RevelationType.MECCAN, 135, 16),
            Surah(21, "الأنبياء", "Al-Anbiya", "The Prophets", RevelationType.MECCAN, 112, 17),
            Surah(22, "الحج", "Al-Hajj", "The Pilgrimage", RevelationType.MEDINAN, 78, 17),
            Surah(23, "المؤمنون", "Al-Mu'minun", "The Believers", RevelationType.MECCAN, 118, 18),
            Surah(24, "النور", "An-Nur", "The Light", RevelationType.MEDINAN, 64, 18),
            Surah(25, "الفرقان", "Al-Furqan", "The Criterion", RevelationType.MECCAN, 77, 18),
            Surah(26, "الشعراء", "Ash-Shu'ara", "The Poets", RevelationType.MECCAN, 227, 19),
            Surah(27, "النمل", "An-Naml", "The Ant", RevelationType.MECCAN, 93, 19),
            Surah(28, "القصص", "Al-Qasas", "The Stories", RevelationType.MECCAN, 88, 20),
            Surah(29, "العنكبوت", "Al-'Ankabut", "The Spider", RevelationType.MECCAN, 69, 20),
            Surah(30, "الروم", "Ar-Rum", "The Romans", RevelationType.MECCAN, 60, 21),
            Surah(31, "لقمان", "Luqman", "Luqman", RevelationType.MECCAN, 34, 21),
            Surah(32, "السجدة", "As-Sajdah", "The Prostration", RevelationType.MECCAN, 30, 21),
            Surah(33, "الأحزاب", "Al-Ahzab", "The Combined Forces", RevelationType.MEDINAN, 73, 21),
            Surah(34, "سبأ", "Saba", "Sheba", RevelationType.MECCAN, 54, 22),
            Surah(35, "فاطر", "Fatir", "Originator", RevelationType.MECCAN, 45, 22),
            Surah(36, "يس", "Ya-Sin", "Ya-Sin", RevelationType.MECCAN, 83, 22),
            Surah(37, "الصافات", "As-Saffat", "Those who set the Ranks", RevelationType.MECCAN, 182, 23),
            Surah(38, "ص", "Sad", "The Letter Sad", RevelationType.MECCAN, 88, 23),
            Surah(39, "الزمر", "Az-Zumar", "The Troops", RevelationType.MECCAN, 75, 23),
            Surah(40, "غافر", "Ghafir", "The Forgiver", RevelationType.MECCAN, 85, 24),
            Surah(41, "فصلت", "Fussilat", "Explained in Detail", RevelationType.MECCAN, 54, 24),
            Surah(42, "الشورى", "Ash-Shuraa", "The Consultation", RevelationType.MECCAN, 53, 25),
            Surah(43, "الزخرف", "Az-Zukhruf", "The Ornaments of Gold", RevelationType.MECCAN, 89, 25),
            Surah(44, "الدخان", "Ad-Dukhan", "The Smoke", RevelationType.MECCAN, 59, 25),
            Surah(45, "الجاثية", "Al-Jathiyah", "The Crouching", RevelationType.MECCAN, 37, 25),
            Surah(46, "الأحقاف", "Al-Ahqaf", "The Wind-Curved Sandhills", RevelationType.MECCAN, 35, 26),
            Surah(47, "محمد", "Muhammad", "Muhammad", RevelationType.MEDINAN, 38, 26),
            Surah(48, "الفتح", "Al-Fath", "The Victory", RevelationType.MEDINAN, 29, 26),
            Surah(49, "الحجرات", "Al-Hujurat", "The Rooms", RevelationType.MEDINAN, 18, 26),
            Surah(50, "ق", "Qaf", "The Letter Qaf", RevelationType.MECCAN, 45, 26),
            Surah(51, "الذاريات", "Adh-Dhariyat", "The Winnowing Winds", RevelationType.MECCAN, 60, 26),
            Surah(52, "الطور", "At-Tur", "The Mount", RevelationType.MECCAN, 49, 27),
            Surah(53, "النجم", "An-Najm", "The Star", RevelationType.MECCAN, 62, 27),
            Surah(54, "القمر", "Al-Qamar", "The Moon", RevelationType.MECCAN, 55, 27),
            Surah(55, "الرحمن", "Ar-Rahman", "The Beneficent", RevelationType.MEDINAN, 78, 27),
            Surah(56, "الواقعة", "Al-Waqi'ah", "The Inevitable", RevelationType.MECCAN, 96, 27),
            Surah(57, "الحديد", "Al-Hadid", "The Iron", RevelationType.MEDINAN, 29, 27),
            Surah(58, "المجادلة", "Al-Mujadila", "The Pleading Woman", RevelationType.MEDINAN, 22, 28),
            Surah(59, "الحشر", "Al-Hashr", "The Exile", RevelationType.MEDINAN, 24, 28),
            Surah(60, "الممتحنة", "Al-Mumtahanah", "She that is to be examined", RevelationType.MEDINAN, 13, 28),
            Surah(61, "الصف", "As-Saf", "The Ranks", RevelationType.MEDINAN, 14, 28),
            Surah(62, "الجمعة", "Al-Jumu'ah", "The Congregation", RevelationType.MEDINAN, 11, 28),
            Surah(63, "المنافقون", "Al-Munafiqun", "The Hypocrites", RevelationType.MEDINAN, 11, 28),
            Surah(64, "التغابن", "At-Taghabun", "Mutual Disillusion", RevelationType.MEDINAN, 18, 28),
            Surah(65, "الطلاق", "At-Talaq", "The Divorce", RevelationType.MEDINAN, 12, 28),
            Surah(66, "التحريم", "At-Tahrim", "The Prohibition", RevelationType.MEDINAN, 12, 28),
            Surah(67, "الملك", "Al-Mulk", "The Sovereignty", RevelationType.MECCAN, 30, 29),
            Surah(68, "القلم", "Al-Qalam", "The Pen", RevelationType.MECCAN, 52, 29),
            Surah(69, "الحاقة", "Al-Haqqah", "The Reality", RevelationType.MECCAN, 52, 29),
            Surah(70, "المعارج", "Al-Ma'arij", "The Ascending Stairways", RevelationType.MECCAN, 44, 29),
            Surah(71, "نوح", "Nuh", "Noah", RevelationType.MECCAN, 28, 29),
            Surah(72, "الجن", "Al-Jinn", "The Jinn", RevelationType.MECCAN, 28, 29),
            Surah(73, "المزمل", "Al-Muzzammil", "The Enshrouded One", RevelationType.MECCAN, 20, 29),
            Surah(74, "المدثر", "Al-Muddaththir", "The Cloaked One", RevelationType.MECCAN, 56, 29),
            Surah(75, "القيامة", "Al-Qiyamah", "The Resurrection", RevelationType.MECCAN, 40, 29),
            Surah(76, "الإنسان", "Al-Insan", "The Human", RevelationType.MEDINAN, 31, 29),
            Surah(77, "المرسلات", "Al-Mursalat", "The Emissaries", RevelationType.MECCAN, 50, 29),
            Surah(78, "النبأ", "An-Naba", "The Tidings", RevelationType.MECCAN, 40, 30),
            Surah(79, "النازعات", "An-Nazi'at", "Those who drag forth", RevelationType.MECCAN, 46, 30),
            Surah(80, "عبس", "'Abasa", "He Frowned", RevelationType.MECCAN, 42, 30),
            Surah(81, "التكوير", "At-Takwir", "The Overthrowing", RevelationType.MECCAN, 29, 30),
            Surah(82, "الانفطار", "Al-Infitar", "The Cleaving", RevelationType.MECCAN, 19, 30),
            Surah(83, "المطففين", "Al-Mutaffifin", "Defrauding", RevelationType.MECCAN, 36, 30),
            Surah(84, "الانشقاق", "Al-Inshiqaq", "The Splitting Open", RevelationType.MECCAN, 25, 30),
            Surah(85, "البروج", "Al-Buruj", "The Mansions of the Stars", RevelationType.MECCAN, 22, 30),
            Surah(86, "الطارق", "At-Tariq", "The Morning Star", RevelationType.MECCAN, 17, 30),
            Surah(87, "الأعلى", "Al-A'la", "The Most High", RevelationType.MECCAN, 19, 30),
            Surah(88, "الغاشية", "Al-Ghashiyah", "The Overwhelming", RevelationType.MECCAN, 26, 30),
            Surah(89, "الفجر", "Al-Fajr", "The Dawn", RevelationType.MECCAN, 30, 30),
            Surah(90, "البلد", "Al-Balad", "The City", RevelationType.MECCAN, 20, 30),
            Surah(91, "الشمس", "Ash-Shams", "The Sun", RevelationType.MECCAN, 15, 30),
            Surah(92, "الليل", "Al-Layl", "The Night", RevelationType.MECCAN, 21, 30),
            Surah(93, "الضحى", "Ad-Duhaa", "The Morning Brightness", RevelationType.MECCAN, 11, 30),
            Surah(94, "الشرح", "Ash-Sharh", "The Relief", RevelationType.MECCAN, 8, 30),
            Surah(95, "التين", "At-Tin", "The Fig", RevelationType.MECCAN, 8, 30),
            Surah(96, "العلق", "Al-'Alaq", "The Clot", RevelationType.MECCAN, 19, 30),
            Surah(97, "القدر", "Al-Qadr", "The Decree", RevelationType.MECCAN, 5, 30),
            Surah(98, "البينة", "Al-Bayyinah", "The Clear Proof", RevelationType.MEDINAN, 8, 30),
            Surah(99, "الزلزلة", "Az-Zalzalah", "The Earthquake", RevelationType.MEDINAN, 8, 30),
            Surah(100, "العاديات", "Al-'Adiyat", "The Courser", RevelationType.MECCAN, 11, 30),
            Surah(101, "القارعة", "Al-Qari'ah", "The Calamity", RevelationType.MECCAN, 11, 30),
            Surah(102, "التكاثر", "At-Takathur", "The Rivalry in World Increase", RevelationType.MECCAN, 8, 30),
            Surah(103, "العصر", "Al-'Asr", "The Declining Day", RevelationType.MECCAN, 3, 30),
            Surah(104, "الهمزة", "Al-Humazah", "The Traducer", RevelationType.MECCAN, 9, 30),
            Surah(105, "الفيل", "Al-Fil", "The Elephant", RevelationType.MECCAN, 5, 30),
            Surah(106, "قريش", "Quraysh", "Quraysh", RevelationType.MECCAN, 4, 30),
            Surah(107, "الماعون", "Al-Ma'un", "The Small Kindnesses", RevelationType.MECCAN, 7, 30),
            Surah(108, "الكوثر", "Al-Kawthar", "The Abundance", RevelationType.MECCAN, 3, 30),
            Surah(109, "الكافرون", "Al-Kafirun", "The Disbelievers", RevelationType.MECCAN, 6, 30),
            Surah(110, "النصر", "An-Nasr", "The Divine Support", RevelationType.MEDINAN, 3, 30),
            Surah(111, "المسد", "Al-Masad", "The Palm Fiber", RevelationType.MECCAN, 5, 30),
            Surah(112, "الإخلاص", "Al-Ikhlas", "The Sincerity", RevelationType.MECCAN, 4, 30),
            Surah(113, "الفلق", "Al-Falaq", "The Daybreak", RevelationType.MECCAN, 5, 30),
            Surah(114, "الناس", "An-Nas", "Mankind", RevelationType.MECCAN, 6, 30)
        )

        fun getByNumber(num: Int): Surah? = ALL_SURAHS.find { it.number == num }

        // Popular surahs for quick filter chips
        val POPULAR_SURAHS = listOf(1, 18, 36, 55, 56, 67)
    }
}
